// GENERATED by tooling/play/generate_subscription.py; edit JSON source only.
import '../../domain/billing/subscription_models.dart';
import 'plan_catalog.dart';
const generatedPlans = <PlanOffer>[
  PlanOffer(SubscriptionTier.free, null, 0, 5, "Teks dan transaksi lokal tanpa batas.", yearlyProductId: null, yearlyRupiah: 0, voiceRequests: 10, ocrRequests: 5, pdfRequests: 1, advanced: false, automaticBackup: false, priority: false, name: "Free", aiLevel: "trial", badge: ""),
  PlanOffer(SubscriptionTier.basic, "finchat_plus_monthly", 15000, 50, "Teks dan transaksi lokal tanpa batas.", yearlyProductId: "finchat_plus_yearly", yearlyRupiah: 149000, voiceRequests: 100, ocrRequests: 100, pdfRequests: null, advanced: true, automaticBackup: true, priority: false, name: "Plus", aiLevel: "standard", badge: "Ekonomis"),
  PlanOffer(SubscriptionTier.pro, "finchat_pro_monthly", 39000, 200, "Teks dan transaksi lokal tanpa batas.", yearlyProductId: "finchat_pro_yearly", yearlyRupiah: 349000, voiceRequests: 500, ocrRequests: 500, pdfRequests: null, advanced: true, automaticBackup: true, priority: true, name: "Pro", aiLevel: "advanced", badge: "PALING DIREKOMENDASIKAN"),
  PlanOffer(SubscriptionTier.unlimited, "finchat_max_monthly", 89000, 500, "Teks dan transaksi lokal tanpa batas.", yearlyProductId: "finchat_max_yearly", yearlyRupiah: 799000, voiceRequests: 1500, ocrRequests: 1500, pdfRequests: null, advanced: true, automaticBackup: true, priority: true, name: "Max", aiLevel: "advanced", badge: "Penggunaan intensif"),
];
