from pathlib import Path
import json, sys
root=Path(__file__).resolve().parents[2]
data=json.loads((root/'assets/config/subscription_plans.json').read_text())
lines=["// GENERATED by tooling/play/generate_subscription.py; edit JSON source only.", "import '../../domain/billing/subscription_models.dart';", "import 'plan_catalog.dart';", "const generatedPlans = <PlanOffer>["]
for p in data['plans']:
    val=lambda x: 'null' if x is None else str(x).lower() if isinstance(x,bool) else json.dumps(x)
    lines.append('  PlanOffer(SubscriptionTier.'+p['tier']+', '+val(p['products'].get('monthly'))+', '+str(p['monthly'])+', '+str(p['ai'])+', '+val('Teks dan transaksi lokal tanpa batas.')+', yearlyProductId: '+val(p['products'].get('yearly'))+', yearlyRupiah: '+str(p['yearly'])+', voiceRequests: '+str(p['voice'])+', ocrRequests: '+str(p['ocr'])+', pdfRequests: '+val(p['pdf'])+', advanced: '+val(p['advanced'])+', automaticBackup: '+val(p['automaticBackup'])+', priority: '+val(p['priority'])+', name: '+val(p['name'])+', aiLevel: '+val(p['aiLevel'])+', badge: '+val(p['badge'])+'),')
lines.append('];')
outputs={'lib/application/billing/generated_plans.dart':'\n'.join(lines)+'\n','server/play-billing/plans.generated.mjs':'// GENERATED; edit assets/config/subscription_plans.json only.\nexport const catalog = '+json.dumps(data['plans'],indent=2)+';\n'}
for name,text in outputs.items():
    path=root/name
    if '--check' in sys.argv:
        if not path.exists() or path.read_text()!=text: raise SystemExit('Stale generated config: '+name)
    else: path.write_text(text)
