"""Generate runtime/release metadata from pubspec; never edit generated versions."""
from pathlib import Path
import argparse
import html
import re
ROOT = Path(__file__).resolve().parents[1]

def version():
    match = re.search(r'^version:\s*["\']?(\d+\.\d+\.\d+\+\d+)["\']?\s*$', (ROOT / 'pubspec.yaml').read_text(), re.M)
    if not match:
        raise ValueError('pubspec must contain a semantic version plus Android build number')
    return match.group(1)

def outputs():
    value = version()
    constants = "// GENERATED by tooling/sync_metadata.py from pubspec.yaml.\nabstract final class AppConstants {\n  static const appName = 'Spenva';\n  static const appVersion = '" + value + "';\n}\n"
    result = {'lib/core/constants/app_constants.dart': constants}
    paragraphs = ''.join('<p>' + html.escape(x).replace('\n', '<br>') + '</p>' for x in (ROOT / 'assets/legal/privacy_id.txt').read_text().split('\n\n'))
    result['docs/privacy/index.html'] = '<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privasi Spenva — draf</title><style>body{max-width:860px;margin:36px auto;padding:0 20px;font:17px/1.65 system-ui}p{overflow-wrap:anywhere}</style><h1>Privasi Spenva</h1><p><strong>Draf source '+value+'. Penerbit/contact/URL penghapusan belum dikonfigurasi. Gunakan render_legal.py dengan profile nyata sebelum publikasi.</strong></p>'+paragraphs+'</html>\n'
    release = (ROOT / '.github/workflows/release.yml').read_text()
    release = re.sub(r"description: 'Release tag, e.g. [^']+'", f"description: 'Release tag, e.g. v{value}'", release)
    release = re.sub(r"default: 'v[^']+'", f"default: 'v{value}'", release)
    result['.github/workflows/release.yml'] = release
    for path in [ROOT / 'README.md', ROOT / 'Ai start here.md', *sorted((ROOT / 'docs').glob('*.md')), *sorted((ROOT / 'docs/playstore').glob('*.md')), ROOT / 'server/play-billing/README.md']:
        if path.name in {'CHANGELOG.md', 'FULL_REPOSITORY_AUDIT.md', 'VALIDATION.md'}: continue
        text = path.read_text()
        if re.search(r'^\*\*Versi sumber: .*?\*\*$', text, re.M):
            result[str(path.relative_to(ROOT))] = re.sub(r'^\*\*Versi sumber: .*?\*\*$', f'**Versi sumber: {value}**', text, flags=re.M)
    return result

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content: stale.append(name)
        else: path.write_text(content)
    if stale: raise SystemExit('Stale metadata; run python3 tooling/sync_metadata.py: ' + ', '.join(stale))
    print('Source version synchronized:', version())
if __name__ == '__main__': main()
